### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by zsennenga**
Some suggestions =)

### CODE REVIEW

**Comment by hayleox** [comment]
Thanks for the awesome contributions! :D My Git skills are a little weak, so I manually merged this by making a new commit of my own.

**Comment by zsennenga** [comment]
Yuuup. Been there. Rebasing can really suck.

**Comment by 21echoes** [comment]
Oh, we also fixed the 500 on `GET campaign/#{ID}`, it should work now :D

**Comment by zsennenga** [comment]
Haha well, there you go.

**Comment by zsennenga** [comment]
Feel free to shoot me an email if you have any more questions.

**Comment by hayleox** [comment]
Thanks guys! Unfortunately I still seem to be getting a 500 error on https://api.patreon.com/campaign/77925?api_key=1745177328c8a1d48100a9b14a1d38c1

**Comment by 21echoes** [comment]
fixed! sorry about that :D

As Zach's PR indicated -- these API's are under active development, are not serving the data that patreon.com runs on, and are not really intended for usage outside of the company. Please use them responsibly, and be understanding as we finalize functionality, format, fix bugs, etc.

**Comment by hayleox** [comment]
No prob, thanks so much for all the help! You guys are awesome :D

**Pull request closed without merging**
